import { createClient, type SupabaseClient, type User } from '@supabase/supabase-js';
import './styles.css';
import { WorldSessionManager, type SaveSource } from './world-session.js';
import { renderWorldCreator } from './world-creator.js';
import { economyPrice } from '../simulation/living-world.js';
import type { WorldId } from '../core/types.js';
import type { LivingWorldKernel } from '../index.js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;
const app = document.querySelector<HTMLDivElement>('#app');
if (!app) throw new Error('APP_ROOT_MISSING');
const supabase: SupabaseClient | null = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;
let clockTimer: number | undefined;
let activeSession: WorldSessionManager | null = null;
let activeKernel: LivingWorldKernel | null = null;

const escapeHtml = (value: string): string => value.replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&#34;' })[character] ?? character);
const realClock = () => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date());
const worldHours = (milliseconds: number) => Math.floor(milliseconds / 3_600_000);
function stopClock(): void { if (clockTimer !== undefined) window.clearInterval(clockTimer); clockTimer = undefined; }

function renderLogin(message = ''): void {
  stopClock(); activeSession = null; activeKernel = null;
  app.innerHTML = `<main class="auth-shell"><section class="auth-card"><div class="brand-mark">✦</div><p class="eyebrow">A living world simulation</p><h1>The Living World</h1><p class="subtle">A world that remembers, changes, and keeps living.</p><div id="auth-content"></div>${message ? `<p class="message" role="status">${escapeHtml(message)}</p>` : ''}</section></main>`;
  const content = document.querySelector<HTMLDivElement>('#auth-content'); if (!content) return;
  content.innerHTML = `<div class="tabs"><button class="tab active" data-auth-tab="login">Log in</button><button class="tab" data-auth-tab="signup">Create account</button></div><form id="auth-form" class="form"><label>Email<input name="email" type="email" autocomplete="email" required /></label><label>Password<input name="password" type="password" autocomplete="current-password" minlength="8" required /></label><div id="username-field" class="hidden"><label>Permanent username<input name="username" type="text" autocomplete="nickname" minlength="2" maxlength="32" /></label></div><button class="primary" type="submit">Log in</button></form><div class="auth-actions"><button class="link-button" id="forgot-password">Forgot password?</button><button class="link-button" id="recover-account">Recover account</button></div>`;
  const form = document.querySelector<HTMLFormElement>('#auth-form'); const password = form?.querySelector<HTMLInputElement>('input[name="password"]'); const submit = form?.querySelector<HTMLButtonElement>('button[type="submit"]'); const usernameField = document.querySelector<HTMLDivElement>('#username-field'); const tabs = [...document.querySelectorAll<HTMLButtonElement>('[data-auth-tab]')]; let mode: 'login' | 'signup' = 'login';
  const setMode = (next: 'login' | 'signup') => { mode = next; tabs.forEach((tab) => tab.classList.toggle('active', tab.dataset.authTab === next)); usernameField?.classList.toggle('hidden', next !== 'signup'); if (submit) submit.textContent = next === 'login' ? 'Log in' : 'Create account'; if (password) password.autocomplete = next === 'login' ? 'current-password' : 'new-password'; };
  tabs.forEach((tab) => tab.addEventListener('click', () => setMode(tab.dataset.authTab as 'login' | 'signup')));
  form?.addEventListener('submit', async (event) => { event.preventDefault(); if (!supabase) return renderLogin('Connect the Supabase environment before using authentication.'); const data = new FormData(form); const email = String(data.get('email') ?? '').trim(); const secret = String(data.get('password') ?? ''); const username = String(data.get('username') ?? '').trim(); if (mode === 'signup' && !username) return renderLogin('A permanent username is required.'); if (submit) submit.disabled = true; const result = mode === 'login' ? await supabase.auth.signInWithPassword({ email, password: secret }) : await supabase.auth.signUp({ email, password: secret, options: { data: { username }, emailRedirectTo: `${window.location.origin}/` } }); if (submit) submit.disabled = false; if (result.error) return renderLogin(result.error.message); if (result.data.session) return showHome(result.data.user); renderLogin('Account created. Check your email if confirmation is required, then log in.'); });
  const sendRecovery = async () => { if (!supabase) return renderLogin('Connect the Supabase environment before using account recovery.'); const email = window.prompt('Enter the email for your account:')?.trim(); if (!email) return; const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); renderLogin(error ? error.message : 'If that account exists, a password recovery email has been sent.'); };
  document.querySelector<HTMLButtonElement>('#forgot-password')?.addEventListener('click', sendRecovery); document.querySelector<HTMLButtonElement>('#recover-account')?.addEventListener('click', sendRecovery);
}

async function showHome(user: User | null): Promise<void> {
  if (!supabase || !user) return renderLogin('Your session could not be established.'); stopClock(); activeSession = new WorldSessionManager(supabase); activeKernel = null;
  const { data: profile } = await supabase.from('profiles').select('username').eq('user_id', user.id).maybeSingle(); const username = profile?.username ?? 'Player';
  app.innerHTML = `<main class="home-shell"><header class="topbar"><div><p class="eyebrow">THE LIVING WORLD</p><h1>Home</h1></div><div class="account-panel"><strong>${escapeHtml(username)}</strong><span id="real-clock">${realClock()}</span><span class="status-pill">● Logged in</span><span class="status-pill cloud">☁ Cloud connected</span><button class="ghost" id="change-password">Change password</button><button class="ghost" id="logout">Log out</button></div></header><section class="hero-card"><p class="eyebrow">YOUR WORLDS</p><h2>Three lives. One world at a time.</h2><p>Each world has its own history, people, memories, economy, rules, and future. World IDs isolate them so nothing can bleed between lives.</p></section><section><div class="section-heading"><h2>Saved worlds</h2><button class="primary compact" id="new-world">+ New game</button></div><div id="world-list" class="world-grid"><div class="loading">Loading worlds…</div></div></section><section class="game-description"><p class="eyebrow">THE GAME</p><h2>A living world, not a predetermined story.</h2><p>The world keeps time, remembers what happened, changes its people and economy, and continues while you are away. Your choices shape what happens, but the world is never required to obey you.</p></section></main>`;
  const clock = document.querySelector<HTMLSpanElement>('#real-clock'); clockTimer = window.setInterval(() => { if (clock) clock.textContent = realClock(); }, 1_000);
  document.querySelector<HTMLButtonElement>('#logout')?.addEventListener('click', async () => { await supabase.auth.signOut(); });
  document.querySelector<HTMLButtonElement>('#change-password')?.addEventListener('click', async () => { const next = window.prompt('Choose a new password (at least 8 characters):') ?? ''; if (next.length < 8) return; const { error } = await supabase.auth.updateUser({ password: next }); if (error) window.alert(error.message); });
  document.querySelector<HTMLButtonElement>('#new-world')?.addEventListener('click', async () => { if (!activeSession) return; try { const kernel = await activeSession.create(user); activeKernel = kernel; renderWorldCreator(app, kernel, activeSession, (nextKernel) => { activeKernel = nextKernel; renderWorld(user, 'cloud'); }); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } });
  await loadWorlds(user);
}

async function loadWorlds(user: User): Promise<void> {
  if (!supabase || !activeSession) return; const list = document.querySelector<HTMLDivElement>('#world-list'); if (!list) return;
  const { data, error } = await supabase.from('worlds').select('id,status,created_at,updated_at,world_time_ms').eq('owner_account_id', user.id).neq('status', 'deleted').order('created_at', { ascending: true });
  if (error) { list.innerHTML = `<div class="error-card">${escapeHtml(error.message)}</div>`; return; }
  const worlds = data ?? [];
  const states = await Promise.all(worlds.map(async (world) => ({ world, state: await activeSession!.load(world.id as WorldId, 'cloud') })));
  const cards = states.map(({ world, state }, index) => {
    const generation = state?.state.generation;
    return `<article class="world-card"><span class="slot">WORLD ${index + 1}</span><h3>${escapeHtml(generation?.spec.name ?? `Living World ${index + 1}`)}</h3><p class="subtle">${generation ? `${generation.spec.genre} · ${generation.npcs.length} initial NPCs` : 'World setup in progress'}</p><p class="world-meta">Status: ${escapeHtml(world.status)} · World time: ${worldHours(Number(world.world_time_ms))}h</p><div class="card-actions"><button class="primary compact" data-load-world="${world.id}">Load</button><button class="danger compact" data-delete-world="${world.id}">Delete</button></div></article>`;
  }).join('');
  const empty = Array.from({ length: Math.max(0, 3 - worlds.length) }, (_, index) => `<article class="world-card empty-card"><span class="slot">WORLD ${worlds.length + index + 1}</span><h3>Empty</h3><p class="subtle">Start a new life here.</p></article>`).join(''); list.innerHTML = cards + empty;
  list.querySelectorAll<HTMLButtonElement>('[data-delete-world]').forEach((button) => button.addEventListener('click', async () => { const id = button.dataset.deleteWorld as WorldId | undefined; if (!id || !window.confirm('Delete this entire world? This cannot be undone.')) return; try { await activeSession?.delete(id); await loadWorlds(user); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } }));
  list.querySelectorAll<HTMLButtonElement>('[data-load-world]').forEach((button) => button.addEventListener('click', async () => { const id = button.dataset.loadWorld as WorldId | undefined; if (!id || !activeSession) return; const source: SaveSource = window.confirm('Load from cloud? Choose Cancel to try local storage.') ? 'cloud' : 'local'; await loadWorld(id, source, user); }));
}

async function loadWorld(worldId: WorldId, source: SaveSource, user: User): Promise<void> {
  if (!activeSession) return; try { const kernel = await activeSession.load(worldId, source); if (!kernel) { window.alert(`No ${source} snapshot exists for this world.`); return; } activeKernel = kernel; if (!kernel.state.generation) { renderWorldCreator(app, kernel, activeSession, (nextKernel) => { activeKernel = nextKernel; renderWorld(user, source); }); return; } renderWorld(user, source); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); }
}

function renderWorld(user: User, source: SaveSource): void {
  if (!activeKernel || !activeSession) return; stopClock();
  const generation = activeKernel.state.generation; const simulation = activeKernel.state.simulation; const economy = simulation?.economy; const currencyName = economy?.currencyName ?? generation?.economy.currencyName ?? 'Currency'; const startingMeal = generation?.economy.prices.find((price) => price.item === 'basic meal'); const price = startingMeal && simulation ? economyPrice(startingMeal.amount, simulation) : startingMeal?.amount ?? 0;
  app.innerHTML = `<main class="home-shell"><header class="topbar"><div><p class="eyebrow">ACTIVE WORLD</p><h1>${escapeHtml(generation?.spec.name ?? 'Living World')}</h1></div><div class="account-panel"><span class="status-pill">● Playing</span><span class="status-pill cloud">${source === 'cloud' ? '☁ Cloud source' : '▣ Local source'}</span><button class="ghost" id="save-world">Save now</button><button class="ghost" id="edit-rules">World rules</button><button class="ghost" id="exit-world">Back to worlds</button></div></header><section class="hero-card"><p class="eyebrow">SIMULATION CORE</p><h2 id="world-time">World time: ${worldHours(activeKernel.state.clock.worldTimeMs)}h</h2><p>World ID: <code>${escapeHtml(activeKernel.state.metadata.id)}</code></p><p>Events recorded: ${activeKernel.state.eventSequence}</p><p>Foundational rules: ${activeKernel.state.constitution.rules.filter((rule) => rule.stability === 'foundational').length} · Evolving rules: ${activeKernel.state.constitution.rules.filter((rule) => rule.stability === 'evolving').length}</p><div class="world-grid"><article class="world-card"><span class="slot">WORLD</span><h3>${generation?.regions.length ?? 0} regions</h3><p class="subtle">${generation?.settlements.length ?? 0} settlements · ${generation?.maps.length ?? 0} fixed maps</p></article><article class="world-card"><span class="slot">PEOPLE</span><h3>${generation?.npcs.length ?? 0} NPCs</h3><p class="subtle">Their moods, energy and daily locations advance with world time.</p></article><article class="world-card"><span class="slot">ECONOMY</span><h3>${currencyName}</h3><p class="subtle" id="economy-summary">Basic meal currently costs ${price} ${currencyName} · trend: ${economy?.trend ?? 'stable'}</p></article></div><p>This is the first living simulation slice. Time advances from real elapsed time; NPC routines and the economy now react to that elapsed world time. Later AI systems will make richer decisions behind these same ownership boundaries.</p></section></main>`;
  const timeLabel = document.querySelector<HTMLHeadingElement>('#world-time'); clockTimer = window.setInterval(() => { if (!activeKernel || !timeLabel) return; activeKernel = activeSession?.advance(activeKernel) ?? activeKernel; const nextSimulation = activeKernel.state.simulation; const nextPrice = startingMeal && nextSimulation ? economyPrice(startingMeal.amount, nextSimulation) : price; timeLabel.textContent = `World time: ${worldHours(activeKernel.state.clock.worldTimeMs)}h`; const economySummary = document.querySelector<HTMLElement>('#economy-summary'); if (economySummary) economySummary.textContent = `Basic meal currently costs ${nextPrice} ${currencyName} · trend: ${nextSimulation?.economy.trend ?? 'stable'}`; }, 1_000);
  document.querySelector<HTMLButtonElement>('#save-world')?.addEventListener('click', async () => { if (!activeKernel || !activeSession) return; try { await activeSession.save(activeKernel, 'manual-save'); window.alert('World saved locally and to cloud.'); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } });
  document.querySelector<HTMLButtonElement>('#edit-rules')?.addEventListener('click', () => { if (!activeKernel || !activeSession) return; renderWorldCreator(app, activeKernel, activeSession, (nextKernel) => { activeKernel = nextKernel; renderWorld(user, source); }); });
  document.querySelector<HTMLButtonElement>('#exit-world')?.addEventListener('click', () => showHome(user));
}

async function bootstrap(): Promise<void> { if (!supabase) return renderLogin('The app is installed, but its Supabase environment is not configured yet.'); const { data: { session } } = await supabase.auth.getSession(); if (session?.user) await showHome(session.user); else renderLogin(); supabase.auth.onAuthStateChange((event, sessionState) => { if (event === 'PASSWORD_RECOVERY') return; if (sessionState?.user) void showHome(sessionState.user); else renderLogin(); }); }
void bootstrap();